# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK.
android.useAndroidX=true

# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

android.suppressUnsupportedCompileSdk=34

# Kotlin DSL configuration
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Kotlin compiler options
kotlin.code.style=official
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true

# Additional Performance Optimizations
org.gradle.workers.max=8
org.gradle.daemon=true
android.enableBuildCache=true
android.enableR8=true
android.lintParallel=true

